### ISSUE TITLE
Import Error: Cannot import name 'Scraper'

### ISSUE THREAD

**Issue by akkatracker** [scrapy/scrapely#75]
I'm trying to build something with the Scrapely library. After a bit of fixing I finally got all install issues out of the way.
Running the sample code:

    from scrapely import Scraper
    s = Scraper()
    url1 = 'http://pypi.python.org/pypi/w3lib/1.1'
    data = {'name': 'w3lib 1.1', 'author': 'Scrapy project', 'description': 'Library of web-related functions'}
    s.train(url1, data)

I get the error:
>Import Error: Cannot import name 'Scraper'

How would I fix this?

**Comment by akkatracker** [comment]
Found out it was because 3 hadn't been released properly yet.

**Comment by ahmedezzeldin93** [comment]
I face this problem now, how did you solve it ? what do you mean by 3 ?

**Comment by akkatracker** [comment]
There is no python 3 port of scrapely yet
