### ISSUE TITLE
add a tag for 0.10 release

### ISSUE THREAD

**Issue by kmike** [scrapy/scrapely#76]
I'm not sure I can add it without breaking auto-release setup - never done this before. //cc @dangra?

Tag should be added for this commit: https://github.com/scrapy/scrapely/commit/62a46daf7a4cb1e68be0b69007e4a52ffa057e25 (I've checked an archive uploaded to pypi for 0.10 versions and compared it with the source code).

**Comment by dangra** [comment]
I think you can just add the tag, it will trigger a travis build and pypi deployment but if the version already exists in pypi the deploy will be rejected.

**Comment by kmike** [comment]
thanks!
