### ISSUE TITLE
Duplicate Values (but valid) in the same html

### ISSUE THREAD

**Issue by anshukpal** [scrapy/scrapely#81]
Hi - I just noticed about this library for unsupervised learning mechanism, I guess this is based on Wrapper Induction. This is a wonderful implementation. I have been playing around for few days. 

What I am trying to understand that if a value, e.g. a flight ticket have two journeys, in the same itinerary (just as a practical example)

Outbound Journey: 
Depart : Newyork 
Arrive: Dallas

Forward Journey: 
Depart: Dallas
Arrive: California

If I I train for "Dallas" value which can be both Arrive & Depart, scrapely is mentioning fragment being already annotated. 

data {'Depart_1' : 'Newyork', 'Arrive_1' : 'Dallas,'Depart_2' : 'Dallas', 'Arrive_2' : 'California}

This is an example for places, can be more like time, date, etc. Also, for return journeys in the same itinerary. 

How can we achieve this using scrapely?

Anshuk

**Comment by ruairif** [comment]
Hi @anshukpal .
If you are using `Scraper.train` it has some [issues](https://github.com/scrapy/scrapely#known-issues) and is really just meant for testing.
If you are using the scrapely [command line tool](https://github.com/scrapy/scrapely#usage-command-line-tool) you should have full control over creating templates to use on other pages that you wish to extract data from.
You can also use a visual tool like [Portia](https://github.com/scrapinghub/portia), which uses scrapely for extraction, to create templates.

**Comment by anshukpal** [comment]
Thanks @ruairif. Yes, I was using .train

So what you are essentially saying, the problem which I mentioned can be handled if I use command line. 
Yes, a visual UI would be extremely helpful, can I install Portia on windows? and guides to that?

Anshuk
