### ISSUE TITLE
Is really Python 3 supported?

### ISSUE THREAD

**Issue by aktywnitu** [scrapy/scrapely#88]
I have problems with running scrapely with Python 3.
Scrapely depends on slybot, which depends on scrapy, which depend on Twisted, which don't support yet Python 3.

Please remove info about supporting Python 3 or give instructions how it can be possible.

**Comment by kmike** [comment]
Scrapely doesn't depend on slybot, and Twisted supports Python 3.

I think the problem could be a pypi version - to get Python 3 support you currently need to install scrapely from github.

**Comment by aktywnitu** [comment]
Thanks for answer.
This was my mistake - it is problem of other project aile:
https://github.com/scrapinghub/aile

which only depends on scrapely. And aile depends on slybot.
Sorry for posting.

**Comment by kmike** [comment]
Yeah, alie doesn't support Python 3 yet.
