### ISSUE TITLE
Please, release a version with a better python3 support

### ISSUE THREAD

**Issue by robsonpeixoto** [scrapy/scrapely#89]
I saw I lot of commits, like this https://github.com/scrapy/scrapely/commit/58f088684eea884c7195ef591b30dca775295d1e, that solve my problem:

```
test/pipeline/test_item_validator.py:3: in <module>
    from newscrawler.pipelines import ItemValidatorPipeline
newscrawler/pipelines.py:12: in <module>
    from scrapely.extractors import safehtml, htmlregion, _TAGS_TO_REPLACE
.eggs/scrapely-0.12.0-py3.5.egg/scrapely/__init__.py:4: in <module>
    from scrapely.htmlpage import HtmlPage, page_to_dict, url_to_page
.eggs/scrapely-0.12.0-py3.5.egg/scrapely/htmlpage.py:8: in <module>
    import re, hashlib, urllib2
E   ImportError: No module named 'urllib2'
```

Is possible to release a new scrapely version?

How can I help?

Thanks

**Comment by victormartinez** [comment]
Guys, I have been using Scrapely for the past few weeks and it would be great to release it with python3 support. Is there any possibility of helping you guys to do that?

**Comment by ruairif** [comment]
Scrapely 0.13.0 has been released with python 3 support
